languaje: php

php:
 - 7.3

before_script:
 - composer self-update

notifications:
   on_success: never
   on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
   - vendor

script:
 - vendor/bin/phpunit test --coverage-test

notifications:
 email: virodriguez37@poligran.edu.co
