languaje: php

php:
    - 7.2
    - 7.3
    - 7.4

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
notifications:
   on_success: never
   on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
   - vendor

script: phpunit

notifications:
 email: virodriguez37@poligran.edu.co


