languaje: php

php:
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source
notifications:
   on_success: never
   on_failure: always
cache:
 directories:
   - $HOME/.composer/cache/files
   - vendor

script:
 - vendor/bin/phpunit test --coverage-test

notifications:
 email: virodriguez37@poligran.edu.co
